pipeline {
    agent any
    parameters {
        string(name: 'env_name', defaultValue: 'test-env-<yourname>-<env_number>', description: "Enter the environment name")
    }
    options {
        timestamps()
        timeout(unit: 'HOURS', time: 2)
        ansiColor('xterm')
        buildDiscarder(
            logRotator(
                daysToKeepStr: '30',
                numToKeepStr: '5'
            )
        )
    }
    stages {
        stage('Checkout Terraform code') {
            steps{
                git branch: "main",
                    credentialsId: 'GITHUB_CREDENTIALS',
                    url: "https://github.com/Lehaa/Environment-terraform"
            }
        }
        stage ('Launch Ec2 Instance') {
            steps{
                script{
                    currentBuild.displayName = (params.env_name)
                    sh '''
                        set -ex
                        source ${WORKSPACE}/variables.sh "$env_name"
                    '''
                    env.tomcat_host = readFile('address.txt').trim()
                }
            }
        }
        stage ('Deploy Application') {
            steps{
                script{

                    build job: 'Deploy-application',
                    parameters: [string(name: 'tomcat_host', value: env.tomcat_host)]
                }
            }
        }
        stage ('Archive artifacts') {
            steps{
                script{
                    archiveArtifacts(artifacts: 'connection_details.txt', followSymlinks:false)
                }
            }
        }
    }
    post {
        cleanup {
            cleanWs()
        }
    }
}