pipeline {
    agent any
    parameters {
        string(name: 'env_name', defaultValue: 'test-env-<yourname>-<env_number>', description: "Please enter the environment name")
    }
    options {
        timestamps()
        timeout(unit: 'HOURS', time: 2)
        ansiColor('xterm')
        buildDiscarder(
            logRotator(
                daysToKeepStr: '30',
                numToKeepStr: '500'
            )
        )
    }
    stages {
        stage('Checkout Terraform code') {
            steps{
                git branch: "main",
                    credentialsId: '1438fbd6-4b4b-4907-a12c-dda8dcc3e2d7',
                    url: "https://github.com/Lehaa/Environment-terraform"
            }
        }
        stage ('Compile Stage') {
            steps{
                script{
                    currentBuild.displayName = (params.env_name)

                sh '''
                    ls
                    source variables.sh
                    source terraform.sh
                '''
                }
            }
        }
    }
    post {
        cleanup {
            cleanWs()
        }
    }
}