pipeline {
    agent any

    stages {
        stage('Checkout Snake project') {
            steps{
                git branch: "master",
                    credentialsId: '1438fbd6-4b4b-4907-a12c-dda8dcc3e2d7',
                    url: "https://github.com/Lehaa/Snake"
            }
        }
        stage ('Compile Stage') {
            steps{
                withMaven(maven : 'maven3'){
                    sh 'mvn clean install'
                }
            }
        }
    }
}