pipeline {
    agent any
    parameters {
        string(name: 'tomcat_ip', defaultValue: '', description: "Please insert the tomcat IP / Hostname")
    }
    stages {
        stage('Checkout Snake project') {
            steps{
                git branch: "master",
                    credentialsId: '1438fbd6-4b4b-4907-a12c-dda8dcc3e2d7',
                    url: "https://github.com/Lehaa/Snake-game"
            }
        }
        stage ('Compile Stage') {
            steps{
                withMaven(maven : 'maven3'){
                    sh 'mvn clean install'
                }
            }
        }
        stage ('Deploy war to tomcat') {
            steps{
                    deploy adapters: [tomcat9(credentialsId: 'tomcat-credentials', path: '', url: 'http://${params.tomcat_ip}:8080/')], contextPath: 'Snake', war: '**/*'
                }
            }
        }
    }
}